### ISSUE TITLE
Small typos in Example handler

### ISSUE THREAD

**Issue by ShimonOhayon** [mineiros-io/terraform-aws-lambda-function#40]
Here: https://github.com/mineiros-io/terraform-aws-lambda-function/blob/master/examples/s3-complete-example/main.tf#L75

and here: https://github.com/mineiros-io/terraform-aws-lambda-function/blob/master/examples/s3-complete-example/README.md#basic-usage
I believe you meant - `handler  = "main.lambda_handler"`

**Comment by soerenmartius** [comment]
Hey @ShimonOhayon ! Thanks for bringing this to our attention. I am gonna provide a fix in a little while and link the PR in this issue.

Again, thanks for reporting this!

**Comment by soerenmartius** [comment]
Fixed in #41
